name: Python application

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read
  id-token: write

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        target: [x86_64]
    defaults:
      run:
        working-directory: ./src/python
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install libopus-dev
        run: |
          sudo apt-get install -y libopus-dev opus-tools autoconf automake libtool gcc make
          export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
          export LIBOPUS_LIB_DIR=/usr/lib/x86_64-linux-gnu/
          export OPUS_NO_PKG=true
      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: publish
          target: ${{ matrix.target }}
          args: -i ${{ matrix.python-version }} --no-sdist --skip-existing -m src/python/Cargo.toml